### ISSUE TITLE
Frontend Upgrade: React fundamental implementation for homepage

### ISSUE THREAD

**Issue by changdiqing** [Apollo1840/StudyTimeBoard#1]
Use React to start building new front-end

mini-spec:
 - A homepage that should look like the current one but build with react
 - Access the new homepage with web api i.g. /modern-beta

**Comment by Apollo1840** [comment]
Try something like this, it could transplant the frontend to react instantly (tested, it is working, at least for GET page).    

    import parse from 'html-react-parser';
    
    
    class App extends React.Component {
    
      state = {
        page: null,
      }
    
      componentDidMount() {
          fetch("/home")
          .then(response => response.text()
              .then(data => this.setState({page: parse(data)})))
        }
    
      render(){return this.state.page;}
    }
    
    export default App;

Then we could change the response from flask to json, and get rid of 'parse'.  Use react components to re-build the page instead.

**Comment by Apollo1840** [comment]
A homepage that should look like the current one but build with react (done)
Access the new homepage with web api i.g. /modern-beta
