### ISSUE TITLE
The citation on the homepage is wrong, should be 10000 hours rule but not 1000 hours rule.

### ISSUE THREAD

**Issue by theSaLi** [Apollo1840/StudyTimeBoard#44]
The citation on the homepage is wrong, should be 10000 hours rule but not 1000 hours rule.

**Comment by changdiqing** [comment]
@Apollo1840 Please check if this bug is valid, did you mean to say 1000 hours instead of 10000 hours in the first place?

**Comment by Apollo1840** [comment]
modfied
